DROP DATABASE IF EXISTS infra_app;
CREATE DATABASE infra_app;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO postgres;
